Remove obsolete attribute 'name' from PLR
openoereb/pyramid_oereb pull request #1274
Opened 2021-07-21 07:43 UTC by vuilleumierc

Closes #1265

2021-07-21 08:05 UTC, voisardf reviewed
Looks good to me, one comment that is not directly related to the issue, but could be done while you are at it

2021-07-21 08:05 UTC, voisardf commented on pyramid_oereb/standard/pyramid_oereb.yml.mako
>        #        - SubTheme2
we could remove this too, as there ar no subthemes in this topic or move the comments to the LandUsePlan where SubThemes are allowed

2021-07-22 09:19 UTC, vvmruder requested changes
There are still some PLRxyz left in docker/config.yaml.tmpl e.g.: https://github.com/openoereb/pyramid_oereb/blob/1265-remove-plr-attribute-name/docker/config.yaml.tmpl#L448

2021-07-22 09:44 UTC, vuilleumierc commented
> There are still some PLRxyz left in docker/config.yaml.tmpl e.g.: https://github.com/openoereb/pyramid_oereb/blob/1265-remove-plr-attribute-name/docker/config.yaml.tmpl#L448

Oh sorry, I thought we wouldn't be using this anymore since the new standard dev setup runs in Docker. I never updated it in my latest PR

2021-07-22 12:33 UTC, vvmruder approved these changes
Sorry for late reply. Yes-feel free to merge.

2021-07-22 12:34 UTC, merged