add DocStrings to adapter.py
openoereb/pyramid_oereb pull request #1412
Opened 2021-11-30 08:02 UTC by svamaa

2021-12-01 14:34 UTC, voisardf commented on pyramid_oereb/lib/adapter.py
> +                application. This can be useful to handle errorcases and threat sessions in
threat should probably be 'to treat'

2021-12-01 14:35 UTC, voisardf approved these changes
thanks

2021-12-06 17:46 UTC, vvmruder requested changes
Please see my comments.

2021-12-06 17:46 UTC, vvmruder commented on pyramid_oereb/core/adapter.py
> +        It uses the current working directory as central point for file handling.
Maybe also add doc for paramteter?

2021-12-06 17:46 UTC, vvmruder commented on pyramid_oereb/core/adapter.py
> +        Args:
I think we can omit Args here at all

2021-12-07 08:10 UTC, vvmruder approved these changes
Thank you! :+1:

2021-12-07 08:14 UTC, merged