Add coverage report
openoereb/pyramid_oereb pull request #1452
Opened 2021-12-22 11:10 UTC by vvmruder

Use Codecov to produce coverage report.

2021-12-22 14:50 UTC, mki-c2c requested changes
CI not running yet

2021-12-22 14:50 UTC, mki-c2c commented on Makefile
> +	$(VENV_BIN)/py.test -vv $(PYTEST_OPTS) --cov-config .coveragerc --cov $(PACKAGE) --cov-report=xml term-missing:skip-covered tests/core
remove term-missing:skip-covered

2021-12-22 14:50 UTC, mki-c2c commented on .github/workflows/ci.yaml
> +          files: ./coverage1.xml,./coverage2.xml
./coverage.xml only

2021-12-23 08:11 UTC, vvmruder commented on Makefile
> +	$(VENV_BIN)/py.test -vv $(PYTEST_OPTS) --cov-config .coveragerc --cov $(PACKAGE) --cov-report=xml term-missing:skip-covered tests/core
thx

2021-12-23 08:11 UTC, vvmruder commented on .github/workflows/ci.yaml
> +          files: ./coverage1.xml,./coverage2.xml
thx

2021-12-23 08:38 UTC, mki-c2c approved these changes
looks nice, thanks, we now have a great tool.

I don't manage to click on the coverage map though, it shows me a page "Sorry, we couldn't find that page"

However, I think it's a good ides to merge (giving the coverage diff with master) and then see how we can live with it. Doing later fixes or additions/removal.

2021-12-23 09:21 UTC, merged