use db host from ENV in test.ini
openoereb/pyramid_oereb pull request #1500
Opened 2022-02-09 10:39 UTC by vvmruder

@mki-c2c Please have a look. Since we have the use case running tests locally inside docker-compose I implemented env variable parsing to set db-host regarding to the env local docker or CI.

This works now for the `test.ini`

Still there is the `test_config.yml` which lacks of this possibility in the moment. You worked on this tests, so I ask you to look for a convenient way to have the db host also parsed from env in here: https://github.com/openoereb/pyramid_oereb/blob/master/tests/conftest.py

2022-02-10 07:46 UTC, mki-c2c commented
this modification seems to break local development tests. In which way do you launch the tests locally ?

2022-02-10 08:15 UTC, vvmruder commented
My and others usecase is to start the docker composition `docker-compose up` and afterwards run `docker-compose exec oereb-server make tests`/`docker-compose exec oereb-server make lint` etc.

This way its completely encapsulated in docker and no other deps are needed. For me this is convenient because using make locally conflicts with system lib versions like proj and I simply cant use it. As far as I know at least @voisardf and @michmuel are using this way too.

But if we use it like this we always need to change the two test config files because the DB-Host inside docker-compose is not `localhost` but `oereb-db`

2022-02-11 07:46 UTC, mki-c2c commented
I have found the library pyaml-env https://dev.to/mkaranasou/python-yaml-configuration-with-environment-variables-parsing-2ha6
It seems to be very suitable for what we want to do, parsing with environment values.
I can write a quick modification to config.py to use this lib.

2022-02-11 09:02 UTC, mki-c2c commented
@vvmruder I just talked to Wolfgang. He reminded me that the c2c tools already include a templating engine. c2ctemplates supports environment variables in the yaml configuration file. This is being used in the schwyz project: https://github.com/camptocamp/schwyz_oereb/blob/V2/config.yaml#L110
I'll check if it also works locally and so we can easily update the test files.

2022-02-11 09:19 UTC, vvmruder commented
> @vvmruder I just talked to Wolfgang. He reminded me that the c2c tools already include a templating engine. c2ctemplates supports environment variables in the yaml configuration file. This is being used in the schwyz project: https://github.com/camptocamp/schwyz_oereb/blob/V2/config.yaml#L110 I'll check if it also works locally and so we can easily update the test files.

Thats ok to me.

2022-02-15 13:54 UTC, kdeininger commented
I think, pyaml-env would have one advantage:

c2ctemplate, which is currently used to render the configuration files, is a template rendering tool using mako or jinja2, that can also access environment variables and provides a lot more features. As it is a separate tool, it needs to be run before the application is started. So we need this additional step, e.g. on container start-up, to respect the currently set environment variables. pyaml-env applies the values of the environment variables on parsing the configuration file. This way, no additional script would be necessary.

2022-02-17 07:55 UTC, mki-c2c commented on tests/core/test_logger.py
> +    app = get_app('tests/resources/test.ini#main', options=os.environ)
hello,
I have huge trouble running tests in a local environment. If there are escaped environment variables (%s) this command fails.
I am testing some stuff, but I would recommend extracting the required values from os.environ like
```
app = get_app('tests/resources/test.ini#main', options={'PGHOST':os.environ.get('PGHOST', 'oereb-db')
```

2022-02-17 07:57 UTC, mki-c2c requested changes
We should continue to work on this.
The setup is not so robust for execution in different contexts.
Either the docker composition has to be very reliable or we must enable running the tests in a local environment.

2022-02-17 07:57 UTC, mki-c2c commented on .github/workflows/ci.yaml
> +          PGHOST: localhost
I would invert the logics:
set PGHOST to localhost by default in the Makefile, and override this by setting oereb-db in docker-compose.yml

2022-02-17 15:26 UTC, vvmruder commented
> We should continue to work on this. The setup is not so robust for execution in different contexts. Either the docker composition has to be very reliable or we must enable running the tests in a local environment.

What is unstable there? I don't experience any issues running it inside the composition?

2022-02-17 16:34 UTC, mki-c2c commented on tests/core/test_logger.py
> +    app = get_app('tests/resources/test.ini#main', options=os.environ)
I have a local environment variable LESSOPEN='| /usr/bin/lesspipe %s'
this variable being present in the environment messes up the get_app command

2022-02-17 16:49 UTC, mki-c2c commented
> > We should continue to work on this. The setup is not so robust for execution in different contexts. Either the docker composition has to be very reliable or we must enable running the tests in a local environment.
> 
> What is unstable there? I don't experience any issues running it inside the composition?

for example the CI is not running in the docker composition, so I find it interesting that the config cannot be messed up with local environment variables.

I extracted a problematic code sample for easier analysis below.

to reproduce my problem, on can open an interactive python session on the docker instance with an environment variable with ```
docker-compose exec -e DUMMY_VAR='bla %s' oereb-server python
```
try to create the app
```
from pyramid.paster import get_app, setup_logging
import os
app = get_app('tests/resources/test.ini#main', options=os.environ)
```
and you get the following error:
`configparser.InterpolationSyntaxError: Error in file /workspace/tests/resources/test.ini: '%' must be followed by '%' or '(', found: '%s'`

2022-02-24 08:04 UTC, mki-c2c commented
hello @vvmruder , do you mind if I do a rebase on this branch ?
Otherwise I'll just merge master, but I fear, it might not be very pretty

2022-02-24 09:36 UTC, vvmruder commented
Sure, go on and rebase it

2022-02-24 10:50 UTC, mki-c2c commented
improved version of makefile with env vars is ready, hope it still works for all of you

2022-02-24 10:51 UTC, mki-c2c approved these changes

2022-02-24 10:51 UTC, mki-c2c commented
decrease in CI coverage is only due to deleted lines which were covered previously

2022-02-24 12:18 UTC, vvmruder reviewed
Since I can't approve my own PR I approve it with this comment :laughing:

2022-02-24 12:18 UTC, vvmruder commented on Makefile
> +docker-tests:
Minor: About this integrated targets it's ok to have them but this means you need to have Make installed on the machine you issue them which is a bit cat bites own tail. These people have to run the docker-compose commands by hand then as they do now.

2022-02-24 12:19 UTC, vvmruder commented
Great work @mki-c2c now it is like I would expect a dev setup :)

@michmuel @voisardf @svamaa => please play around with it. Hope you are satisfied too

2022-02-25 08:41 UTC, merged